import { useMemo, useState } from "react";

type Page = "home" | "about" | "products" | "catalog" | "distributors" | "insights" | "contact";

const nav: { label: string; page: Page }[] = [
  { label: "Perusahaan", page: "about" }, { label: "Produk", page: "products" },
  { label: "Katalog PDF", page: "catalog" }, { label: "Distributor", page: "distributors" },
  { label: "Wawasan", page: "insights" },
];

const products = [
  ["Almeta Locking Plate", "AM-LP-021", "Titanium", "Trauma", "Distal Radius"],
  ["Almeta Clavicle Plate", "AM-CP-014", "Stainless Steel", "Trauma", "Superior"],
  ["Almeta DHS System", "AM-DHS-009", "Stainless Steel", "Hip", "135°"],
  ["Almeta Tibia Nail", "AM-TN-031", "Titanium", "Trauma", "Cannulated"],
  ["Almeta Hemi Hip", "AM-HH-006", "Cobalt Chrome", "Arthroplasty", "Modular"],
  ["Almeta Cannulated Screw", "AM-CS-018", "Titanium", "Trauma", "4.0 mm"],
];

function Arrow() { return <span aria-hidden="true" className="inline-flex size-5 items-center justify-center rounded-full border border-current text-xs">→</span>; }
function Plate({ variant = 0 }: { variant?: number }) { return <div className={`plate plate-${variant}`}><i /><b /><em /><span /><small /></div>; }

export default function App() {
  const [page, setPage] = useState<Page>("home");
  const [locale, setLocale] = useState("ID");
  const [menu, setMenu] = useState(false);
  const [sent, setSent] = useState(false);
  const go = (next: Page) => { setPage(next); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const labels = locale === "ID" ? { rfq: "Minta Penawaran", contact: "Hubungi kami", title: "Solusi perangkat medis untuk pergerakan yang lebih baik." } : { rfq: "Request a quote", contact: "Contact us", title: "Medical device solutions for better movement." };
  return <div className="min-h-full bg-[#f4f7f5] text-[#112b2e] selection:bg-[#b8d8c8]">
    <header className="sticky top-0 z-30 border-b border-[#d9e0dc] bg-[#f4f7f5]/95 backdrop-blur">
      <div className="mx-auto flex h-[76px] max-w-[1440px] items-center justify-between px-5 md:px-10">
        <button onClick={() => go("home")} className="brand text-left" aria-label="Almeta Medisys beranda"><span className="brand-mark">a</span><span>almeta<small>MEDISYS</small></span></button>
        <nav className="hidden items-center gap-7 lg:flex">{nav.map((item) => <button key={item.page} onClick={() => go(item.page)} className={`nav-link ${page === item.page ? "active" : ""}`}>{item.label}</button>)}</nav>
        <div className="flex items-center gap-3"><button onClick={() => setLocale(locale === "ID" ? "EN" : "ID")} className="text-[11px] font-bold tracking-[.14em] text-[#47605d]">{locale} <span className="ml-1 text-[#8ca09a]">/ {locale === "ID" ? "EN" : "ID"}</span></button><button onClick={() => go("contact")} className="hidden rounded-full bg-[#143b3e] px-5 py-3 text-[11px] font-bold tracking-[.1em] text-white transition hover:bg-[#247068] sm:block">{labels.rfq}</button><button onClick={() => setMenu(!menu)} className="grid size-10 place-items-center lg:hidden" aria-label="Buka menu"><span className="text-xl">{menu ? "×" : "☰"}</span></button></div>
      </div>
      {menu && <div className="border-t border-[#d9e0dc] bg-[#f4f7f5] px-5 py-4 lg:hidden">{nav.map(item => <button key={item.page} onClick={() => go(item.page)} className="block w-full py-3 text-left text-sm font-medium">{item.label}</button>)}<button onClick={() => go("contact")} className="mt-2 rounded-full bg-[#143b3e] px-5 py-3 text-xs font-bold text-white">{labels.rfq}</button></div>}
    </header>
    {page === "home" && <Home go={go} labels={labels} />}
    {page === "about" && <About go={go} />}
    {page === "products" && <Products go={go} />}
    {page === "catalog" && <Catalog go={go} />}
    {page === "distributors" && <Distributors go={go} />}
    {page === "insights" && <Insights />}
    {page === "contact" && <Contact sent={sent} setSent={setSent} />}
    <Footer go={go} />
  </div>;
}

function Home({ go, labels }: { go: (p: Page) => void; labels: { rfq: string; contact: string; title: string } }) { return <>
  <main>
    <section className="hero-grid relative overflow-hidden bg-[#113538] text-white"><div className="absolute inset-y-0 right-0 w-[46%] bg-[#c7ded0]" /><div className="relative mx-auto grid min-h-[595px] max-w-[1440px] grid-cols-1 px-5 md:px-10 lg:grid-cols-[1.16fr_.84fr]">
      <div className="flex flex-col justify-between py-14 lg:py-20"><p className="eyebrow text-[#a8d2bd]">HEALTHCARE DISTRIBUTION · INDONESIA</p><div><h1 className="max-w-3xl font-display text-5xl leading-[.98] tracking-[-.055em] md:text-7xl">{labels.title}</h1><p className="mt-7 max-w-lg text-base leading-7 text-[#c1d0cc]">Mendistribusikan solusi ortopedi dan alat kesehatan dengan standar manufaktur yang terpercaya sejak 1998.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => go("products")} className="rounded-full bg-[#b9dac8] px-6 py-3.5 text-xs font-bold tracking-[.08em] text-[#113538]">JELAJAHI PRODUK</button><button onClick={() => go("contact")} className="rounded-full border border-white/35 px-6 py-3.5 text-xs font-bold tracking-[.08em]">{labels.rfq.toUpperCase()}</button></div></div><div className="flex gap-8 text-xs text-[#a8beb8]"><span><b className="block text-xl text-white">28+</b> tahun pengalaman</span><span><b className="block text-xl text-white">7000 m²</b> fasilitas manufaktur</span></div></div>
      <div className="relative hidden items-center justify-center lg:flex"><div className="hero-orbit" /><Plate variant={1} /><div className="absolute bottom-12 left-10 max-w-[180px] border-l border-[#143b3e]/30 pl-4 text-xs leading-5 text-[#315451]">Sistem implan ortopedi yang direkayasa untuk ketepatan klinis.</div></div>
    </div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-14 md:px-10"><div className="grid gap-px overflow-hidden rounded-sm bg-[#d8e1dd] md:grid-cols-4">{[["01", "Produk ber-TKDN", "Mendukung pengadaan alat kesehatan dalam negeri."], ["02", "Terdaftar AKD", "Dokumentasi dan kepatuhan regulasi yang terjaga."], ["03", "e-Katalog", "Akses lebih mudah untuk kebutuhan instansi."], ["04", "Dukungan Marthys", "Kapasitas pabrik dan pengalaman manufaktur." ]].map(x => <div key={x[0]} className="bg-[#f4f7f5] p-7"><span className="font-mono text-[10px] text-[#71918a]">{x[0]}</span><h3 className="mt-9 text-lg font-semibold">{x[1]}</h3><p className="mt-3 text-sm leading-6 text-[#607572]">{x[2]}</p></div>)}</div></section>
    <section className="border-y border-[#d8e1dd] bg-white"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 py-20 md:px-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">PORTOFOLIO</p><h2 className="mt-4 font-display text-4xl leading-none tracking-[-.04em]">Dirancang untuk mendukung setiap langkah pemulihan.</h2><button onClick={() => go("products")} className="mt-8 flex items-center gap-3 text-xs font-bold tracking-[.1em]">LIHAT SEMUA PRODUK <Arrow /></button></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3">{products.slice(0, 3).map((p, i) => <button onClick={() => go("products")} className="group text-left" key={p[0]}><div className="grid aspect-[.9] place-items-center bg-[#e8efeb] transition group-hover:bg-[#d5e8de]"><Plate variant={i} /></div><p className="mt-3 text-[10px] font-bold tracking-[.1em] text-[#71847f]">{p[3]}</p><h3 className="mt-1 text-sm font-semibold">{p[0]}</h3></button>)}</div></div></section>
    <section className="mx-auto grid max-w-[1440px] gap-8 px-5 py-20 md:px-10 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-sm bg-[#e2eee7] p-8 md:p-12"><p className="eyebrow">UNTUK MITRA DISTRIBUSI</p><h2 className="mt-8 max-w-xl font-display text-4xl leading-none tracking-[-.04em]">Jangkau lebih banyak fasilitas kesehatan bersama kami.</h2><button onClick={() => go("distributors")} className="mt-9 rounded-full bg-[#143b3e] px-6 py-3.5 text-xs font-bold tracking-[.1em] text-white">JADI DISTRIBUTOR</button></div><div className="border border-[#d8e1dd] p-8 md:p-12"><p className="eyebrow">INSIGHT TERBARU</p><h3 className="mt-8 font-display text-3xl leading-tight tracking-[-.04em]">Memahami material implan: titanium dan stainless steel.</h3><p className="mt-4 text-sm leading-6 text-[#607572]">Panduan ringkas untuk memahami karakteristik material dalam aplikasi ortopedi.</p><button onClick={() => go("insights")} className="mt-8 flex items-center gap-3 text-xs font-bold tracking-[.1em]">BACA ARTIKEL <Arrow /></button></div></section>
  </main></> }

function PageHead({ kicker, title, children }: { kicker: string; title: string; children?: React.ReactNode }) { return <section className="border-b border-[#d8e1dd] bg-[#e7f0ea]"><div className="mx-auto max-w-[1440px] px-5 py-16 md:px-10 md:py-24"><p className="eyebrow">{kicker}</p><h1 className="mt-5 max-w-4xl font-display text-5xl leading-[.95] tracking-[-.055em] md:text-7xl">{title}</h1>{children}</div></section> }
function About({ go }: { go: (p: Page) => void }) { return <main><PageHead kicker="TENTANG KAMI" title="Kepercayaan dibangun dari presisi." ><p className="mt-7 max-w-xl text-base leading-7 text-[#55706a]">Almeta Medisys adalah mitra distribusi perangkat medis yang tumbuh dari fondasi manufaktur ortopedi Indonesia.</p></PageHead><section className="mx-auto grid max-w-[1440px] gap-14 px-5 py-20 md:px-10 lg:grid-cols-[.8fr_1.2fr]"><p className="eyebrow">BAGIAN DARI MARTHYS GROUP</p><div><h2 className="font-display text-4xl leading-tight tracking-[-.04em]">Kami menghubungkan inovasi manufaktur dengan kebutuhan pelayanan kesehatan di Indonesia.</h2><p className="mt-8 max-w-2xl leading-7 text-[#55706a]">Berakar dari PT Marthys Orthopaedic Indonesia—produsen implan ortopedi pertama di Indonesia yang berdiri pada 1998—Almeta Medisys membawa produk dan layanan kepada rumah sakit, institusi, dan jaringan distributor secara tepat dan bertanggung jawab.</p><button onClick={() => go("contact")} className="mt-8 rounded-full bg-[#143b3e] px-6 py-3 text-xs font-bold tracking-[.1em] text-white">KENALI KAMI</button></div></section><section className="border-y border-[#d8e1dd] bg-white"><div className="mx-auto max-w-[1440px] px-5 py-16 md:px-10"><p className="eyebrow">PERJALANAN KAMI</p><div className="mt-10 grid gap-px bg-[#d8e1dd] md:grid-cols-4">{[["1998","Marthys Orthopaedic berdiri di Indonesia."],["2010","Kapasitas manufaktur Prigen terus berkembang."],["2024","Almeta Medisys hadir sebagai fokus distribusi."],["Hari ini","Melayani kebutuhan alkes di seluruh Nusantara."]].map(x=><div className="bg-white p-6" key={x[0]}><strong className="font-display text-3xl">{x[0]}</strong><p className="mt-8 text-sm leading-6 text-[#607572]">{x[1]}</p></div>)}</div></div></section></main> }
function Products({ go }: { go: (p: Page) => void }) { const [filter,setFilter]=useState("Semua"); const shown=useMemo(()=>filter==="Semua"?products:products.filter(p=>p[3]===filter),[filter]); return <main><PageHead kicker="KATALOG PRODUK" title="Solusi yang berdiri di atas bukti." ><p className="mt-7 max-w-2xl text-base leading-7 text-[#55706a]">Rangkaian implan ortopedi dan perangkat medis untuk mendukung prosedur dengan ketepatan tinggi.</p></PageHead><section className="mx-auto max-w-[1440px] px-5 py-10 md:px-10"><div className="mb-10 flex flex-wrap items-center gap-2">{["Semua","Trauma","Hip","Arthroplasty"].map(f=><button onClick={()=>setFilter(f)} key={f} className={`rounded-full border px-4 py-2 text-xs font-semibold ${filter===f?"border-[#143b3e] bg-[#143b3e] text-white":"border-[#cbd8d2] text-[#56706a]"}`}>{f}</button>)}<span className="ml-auto hidden text-xs text-[#71847f] md:block">{shown.length} produk ditemukan</span></div><div className="grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{shown.map((p,i)=><article key={p[1]} className="group"><div className="relative grid aspect-[1.15] place-items-center overflow-hidden bg-[#e3ece7]"><span className="absolute left-4 top-4 font-mono text-[10px] text-[#668079]">{p[1]}</span><Plate variant={i}/><button onClick={()=>go("contact")} className="absolute bottom-4 right-4 grid size-10 place-items-center rounded-full bg-[#143b3e] text-white opacity-0 transition group-hover:opacity-100"><Arrow /></button></div><div className="mt-4 flex justify-between gap-2"><div><p className="text-[10px] font-bold tracking-[.1em] text-[#77918a]">{p[3]} · {p[2]}</p><h2 className="mt-1 text-lg font-semibold">{p[0]}</h2></div><span className="pt-1 text-xs text-[#657c76]">{p[4]}</span></div></article>)}</div></section></main> }
function Catalog({ go }: { go: (p: Page) => void }) { return <main><PageHead kicker="KATALOG DIGITAL" title="Satu referensi untuk kebutuhan klinis Anda." /><section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 md:px-10 lg:grid-cols-[1fr_.75fr]"><div className="relative min-h-[430px] overflow-hidden bg-[#143b3e] p-10 text-white"><div className="absolute right-0 top-0 h-full w-1/3 bg-[#b8d7c5]"/><div className="relative flex h-full flex-col justify-between"><div><span className="eyebrow text-[#afd4bf]">ALMETA MEDISYS</span><h2 className="mt-10 font-display text-5xl leading-none">Product<br/>Catalogue<br/>2026</h2></div><p className="text-xs tracking-[.12em] text-[#bad0c6]">ORTHOPAEDIC & MEDICAL DEVICES</p></div></div><div className="flex flex-col justify-center"><p className="eyebrow">EDISI TERBARU</p><h2 className="mt-5 font-display text-4xl tracking-[-.04em]">Katalog Produk 2026</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#607572]">Temukan rangkaian produk, informasi seri, material, dan spesifikasi dasar dalam satu dokumen yang mudah dibagikan.</p><div className="mt-8 flex gap-3"><button className="rounded-full bg-[#143b3e] px-6 py-3.5 text-xs font-bold tracking-[.08em] text-white">UNDUH PDF · 12 MB</button><button onClick={()=>go("contact")} className="rounded-full border border-[#b9c9c2] px-6 py-3.5 text-xs font-bold tracking-[.08em]">BUTUH BANTUAN?</button></div></div></section></main> }
function Distributors({ go }: { go: (p: Page) => void }) { const [region,setRegion]=useState("Semua Wilayah"); const data=[["PT Medika Nusantara","Jakarta & Jawa Barat"],["CV Prima Orthomed","Jawa Tengah & DIY"],["PT Surya Medika Abadi","Jawa Timur & Bali"],["PT Borneo Healthcare","Kalimantan"],["PT Citra Sehat Makassar","Sulawesi"],["PT Medis Jaya Papua","Indonesia Timur"]]; const shown=region==="Semua Wilayah"?data:data.filter(d=>d[1].includes(region)); return <main><PageHead kicker="JARINGAN DISTRIBUSI" title="Hadir lebih dekat di seluruh Indonesia." ><p className="mt-7 max-w-xl text-base leading-7 text-[#55706a]">Jaringan mitra yang memahami kebutuhan fasilitas kesehatan di wilayahnya masing-masing.</p></PageHead><section className="mx-auto max-w-[1440px] px-5 py-12 md:px-10"><select value={region} onChange={e=>setRegion(e.target.value)} className="mb-9 rounded-full border border-[#cbd8d2] bg-transparent px-5 py-3 text-sm outline-none"><option>Semua Wilayah</option><option>Jawa</option><option>Kalimantan</option><option>Sulawesi</option></select><div className="grid gap-px bg-[#d8e1dd] sm:grid-cols-2 lg:grid-cols-3">{shown.map((d,i)=><article className="bg-[#f4f7f5] p-7" key={d[0]}><div className="grid size-12 place-items-center rounded-full bg-[#d8e9df] font-display text-xl text-[#28594f]">{String.fromCharCode(65+i)}</div><h2 className="mt-10 text-lg font-semibold">{d[0]}</h2><p className="mt-2 text-sm text-[#607572]">{d[1]}</p><button className="mt-7 text-xs font-bold tracking-[.1em] text-[#315d56]">HUBUNGI MITRA →</button></article>)}</div></section><section className="bg-[#143b3e] text-white"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 px-5 py-14 md:px-10 lg:flex-row lg:items-center"><div><p className="eyebrow text-[#a9d3bd]">KEMITRAAN</p><h2 className="mt-4 font-display text-4xl tracking-[-.04em]">Tumbuh bersama Almeta Medisys.</h2></div><button onClick={()=>go("contact")} className="rounded-full bg-[#b9dac8] px-6 py-3.5 text-xs font-bold tracking-[.1em] text-[#123538]">DAFTAR JADI DISTRIBUTOR</button></div></section></main> }
function Insights() { return <main><PageHead kicker="WAWASAN" title="Pengetahuan untuk keputusan yang lebih baik." /><section className="mx-auto max-w-[1440px] px-5 py-12 md:px-10"><div className="grid gap-7 lg:grid-cols-[1.15fr_.85fr]">{[["MATERIAL", "Memahami material implan: titanium dan stainless steel", "06 Sep 2026"],["PENGADAAN", "Menyiapkan kebutuhan alat kesehatan untuk fasilitas pelayanan", "29 Agu 2026"],["ORTOPEDI", "Mengapa presisi desain penting dalam sistem fiksasi tulang", "12 Agu 2026"]].map((x,i)=><article className={`border-b border-[#d8e1dd] pb-7 ${i===0?"lg:row-span-2 lg:border-b-0":""}`} key={x[1]}><div className={`mb-5 ${i===0?"h-64":"h-32"} bg-[#dbe9e1] p-5`}><span className="eyebrow text-[#51736a]">{x[0]}</span></div><p className="text-[10px] font-bold tracking-[.1em] text-[#77918a]">{x[2]}</p><h2 className={`${i===0?"text-3xl":"text-xl"} mt-2 max-w-lg font-display leading-tight tracking-[-.035em]`}>{x[1]}</h2><button className="mt-5 text-xs font-bold tracking-[.1em]">BACA ARTIKEL →</button></article>)}</div></section></main> }
function Contact({ sent, setSent }: { sent: boolean; setSent: (v:boolean)=>void }) { return <main><PageHead kicker="KONTAK & RFQ" title="Mari mulai percakapan." ><p className="mt-7 max-w-xl text-base leading-7 text-[#55706a]">Sampaikan kebutuhan produk atau minat kemitraan Anda. Tim kami akan merespons pada hari kerja.</p></PageHead><section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-16 md:px-10 lg:grid-cols-[.7fr_1.3fr]"><aside><p className="eyebrow">ALMETA MEDISYS</p><div className="mt-8 space-y-6 text-sm leading-6 text-[#55706a]"><p><b className="block text-[#183a3b]">Kantor pusat</b>Jl. Raya Prigen, Pasuruan<br/>Jawa Timur, Indonesia</p><p><b className="block text-[#183a3b]">Hubungi kami</b>+62 341 000 000<br/>hello@almetamedisys.co.id</p><p><b className="block text-[#183a3b]">Jam operasional</b>Senin–Jumat · 08.00–17.00 WIB</p></div></aside><form onSubmit={e=>{e.preventDefault();setSent(true)}} className="rounded-sm bg-white p-7 md:p-10">{sent?<div className="py-16 text-center"><span className="text-4xl">✓</span><h2 className="mt-5 font-display text-3xl">Permintaan Anda telah diterima.</h2><p className="mt-3 text-sm text-[#607572]">Kami akan menghubungi Anda secepatnya.</p></div>:<><div className="flex gap-3 border-b border-[#d8e1dd] pb-5"><span className="rounded-full bg-[#143b3e] px-4 py-2 text-xs font-bold text-white">REQUEST FOR QUOTATION</span><span className="px-3 py-2 text-xs text-[#78908a]">JADI DISTRIBUTOR</span></div><div className="mt-7 grid gap-5 sm:grid-cols-2">{[["Nama lengkap","text"],["Instansi / perusahaan","text"],["Email","email"],["Telepon / WhatsApp","tel"]].map(x=><label key={x[0]} className="text-xs font-bold tracking-[.06em] text-[#49645d]">{x[0]}<input required type={x[1]} className="mt-2 w-full border-b border-[#cbd8d2] py-3 text-sm font-normal outline-none focus:border-[#143b3e]" /></label>)}</div><label className="mt-6 block text-xs font-bold tracking-[.06em] text-[#49645d]">Produk atau minat<input className="mt-2 w-full border-b border-[#cbd8d2] py-3 text-sm font-normal outline-none focus:border-[#143b3e]" placeholder="Contoh: Almeta Locking Plate" /></label><label className="mt-6 block text-xs font-bold tracking-[.06em] text-[#49645d]">Pesan<textarea required className="mt-2 h-24 w-full border-b border-[#cbd8d2] py-3 text-sm font-normal outline-none focus:border-[#143b3e]" /></label><button className="mt-8 rounded-full bg-[#143b3e] px-6 py-3.5 text-xs font-bold tracking-[.1em] text-white">KIRIM PERMINTAAN</button></>}</form></section></main> }
function Footer({ go }: { go: (p:Page)=>void }) { return <footer className="border-t border-[#d8e1dd] bg-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 md:grid-cols-[1.4fr_1fr_1fr] md:px-10"><div><button onClick={()=>go("home")} className="brand"><span className="brand-mark">a</span><span>almeta<small>MEDISYS</small></span></button><p className="mt-5 max-w-xs text-sm leading-6 text-[#607572]">Medical distribution partner for precise, accessible healthcare solutions.</p></div><div><p className="eyebrow">NAVIGASI</p>{nav.slice(0,4).map(x=><button onClick={()=>go(x.page)} key={x.page} className="mt-3 block text-sm text-[#55706a]">{x.label}</button>)}</div><div><p className="eyebrow">KONTAK</p><p className="mt-3 text-sm leading-6 text-[#55706a]">hello@almetamedisys.co.id<br/>+62 341 000 000</p></div></div><div className="border-t border-[#d8e1dd] px-5 py-5 text-center text-[10px] tracking-[.08em] text-[#7c918b]">© 2026 ALMETA MEDISYS · A MEMBER OF MARTHYS GROUP</div></footer> }
